### ISSUE TITLE
Unable to load dynamic library

### ISSUE THREAD

**Issue by jolly7481** [tarantool/tarantool-php#125]
Installed via pecl install Tarantool-PHP/Tarantool-beta

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/tarantool.so' - /usr/lib64/php/modules/tarantool.so: undefined symbol: tarantool_schema_destroy in Unknown on line 0
PHP 5.6.31 (cli) (built: Jul  6 2017 08:16:47) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

**Comment by bigbes** [comment]
Hello, @jolly7481
Version from PECL is obsolete, try to install from source or use deb/rpm packages

PS I haven't maintained PECL repo for a while, since i've not found any OK tool to maintain it (https://pirum.symfony.com/ is obsolete now).
Future plan is to move to pickle. Currently I don't have available time for this, but I'm opened for PR's.

**Comment by bigbes** [comment]
Feel free to reopen this issue, if installing from source won't work for you

**Comment by jolly7481** [comment]
Thanks for the info I was able to install it from source.. :D
